### PR TITLE
SIP-294 fix: move external under name

### PR DESCRIPTION
**Pull request by Bankamah**

### CODE REVIEW

**Review by nicomaurer — DISMISSED** [review]

**Review by erik-perri — DISMISSED** [review]

**Comment by iBotPeaches** [comment]
In `docker-compose-services`, we removed `external` entirely to stop the warning. In this one we just moved it to a property of true. Can you dig into the differences with this? Did we do the last one wrong? Or should we align?

**Comment by Bankamah** [comment]
From my checks, if the external is removed docker-compose will not consider it as external even if though it will work. That is why the property `true` with external was set. Additional link [Docker network](https://docs.docker.com/compose/compose-file/compose-file-v2/#network-configuration-reference)

**Comment by iBotPeaches** [comment]
> From my checks, if the external is removed docker-compose will not consider it as external even if though it will work. That is why the property `true` with external was set. Additional link [Docker network](https://docs.docker.com/compose/compose-file/compose-file-v2/#network-configuration-reference)

Okay, lets add external to the other one then w/ true. These are both `st-internal` which is created prior to the compose files so all projects can use that network.

**Comment by Bankamah** [comment]
Sounds good.

**Review by iBotPeaches — APPROVED** [review]

**Review by erik-perri — APPROVED** [review]

**Review by Vacoris — APPROVED** [review]

**Review by chase-patterson — APPROVED** [review]

**Review by joeladam518 — APPROVED** [review]

**Review by jweberst — APPROVED** [review]

**Pull request merged**
